username: 'username'
name: 'You Name'
domain: 'your-domain.tld'
https: true
summary: 'your summary'
icon_url: 'https://you-avatar-url'
pass: '<bcrypt password hash>'
#favicon_url: '/static/favicon.png'
#profile_metadata:
#    name1: 'value'
#    name2: 'value2'
#hide_following: true
#manually_approves_followers: false
#aliases:
#    - "http://example.com/users/name"
#    - ...
#theme:
#    style: "light" #or "dark"
#    # accent color
#    color: "#1d781d" # (green, default for light)
          # "#33ff00" # (lime green, default for dark)
#emojis: '' # space-separated emojis
#emoji_tpl: # emoji template
#  '<img src="/static/twemoji/{filename}.svg" alt="{raw}" class="emoji">'
#blacklist:
#    - "example.com"
#    - ...
#disable_webmentions: false
#replies_in_stream: false
#days_to_keep: 14
